#!/bin/sh

#Bob forks:
base=`pwd`
for repo in vessel_icing marine_visibility drift_olenic sea-ice evo_mos emily_intercompare hello opendrift ENIAC Icepack ufs-s2s-evaluation SIDFEx ice_scoring CICE ufs-weather-model global-workflow newdrift mmablib toolbox newsys 
#emc:
do
  if [ ! -d $repo ] ; then
    git clone --recursive https://github.com/rgrumbine/$repo $repo
    cd $repo 
    git submodule update --init --recursive
    git checkout develop
    cd $base
  fi
done


#for repo in concentration drift_grumbine 
#Renaming involved:
if [ ! -d drift ] ; then
  git clone https://github.com/NOAA-EMC/drift_grumbine drift
  cd drift
  git checkout sidfex
fi
cd $base

if [ ! -d concentration ] ; then
  git clone https://github.com/NOAA-EMC/concentration 
  cd concentration
  git checkout develop
fi
cd $base

#Cannot fork, just copy:
if [ ! -d soca-science ] ; then
  git clone https://github.com/JCSDA-internal/soca-science.git 
  cd soca-science
  git checkout develop
fi

exit

module purge
module-discovery

#mmablib:
cd sorc
./makelibombF.sh
./makelibombC.sh
#ice_scoring
#-- create a makeall.sh

#CICE:
?

#ufs-weather-model
#(ca. 20 minutes)
#build.sh -- with appropriate environment
