#!/bin/sh

base=`pwd`

#Bob's repos + forks:
for repo in vessel_icing marine_visibility drift_olenic evo_mos Icepack ufs-s2s-evaluation SIDFEx ice_scoring newdrift mmablib toolbox newsys NOAA-Internship-Project emcpy meta_ice
do
  if [ ! -d $repo ] ; then
    git clone --recursive https://github.com/rgrumbine/$repo $repo
    cd $repo 
    git submodule update --init --recursive
    git checkout develop
    cd $base
  fi
done

#EMC repos
for repo in drift_grumbine seaice-concentration
do
if [ ! -d $repo ] ; then
  git clone https://github.com/NOAA-EMC/$repo 
  cd $repo 
  git submodule update --init --recursive
  git checkout develop
  cd $base
fi
done
cd $base

# Larger repos
# cice = ~1 min
# ufs-weather ~7 min
# global-workflow ~15 min
for repo in CICE ufs-weather-model global-workflow 
do
  if [ ! -d $repo ] ; then
    git clone --recursive https://github.com/rgrumbine/$repo $repo
    cd $repo 
    git submodule update --init --recursive
    git checkout develop
    cd $base
exit

# elementary building of executables, libraries, finding modules
module purge
module-discovery

#mmablib:
cd sorc
./makelibombF.sh
./makelibombC.sh
#ice_scoring
#-- create a makeall.sh

#CICE:
?

#ufs-weather-model
#(ca. 20 minutes)
#build.sh -- with appropriate environment
